#!/bin/bash

# job identification number
id=1
# check if id is given as input parameter
# (like when running in condor job system)
if [ $# -ne 0 ]
then
    id=$1
fi

tar -xzf hic_HQ-osg.tar.gz
sleep 2

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load python/3.5.2 all-pkgs gcc boost hdf5 || exit 1


# start trento events
####################################################################
#######################################################################
#########################################################################
###########################################################################
cd hic_HQ-osg/
cp ../args.conf .
./run-events $1

cd ../    
tar czf results$1.tar.gz hic_HQ-osg/results    

# transfer results
# try to be fault-tolerant
#globus() {
#  globus-url-copy \
#  -verbose -create-dest -restart -stall-timeout 30 results$1.tar.gz \
#  gsiftp://ntheoryfs01.phy.duke.edu/var/phy/project/nukeserv/yx59/TEST/
#}

#for i in {1..5}; do
#  globus && break
#  sleep 5 && false
#done || \
#  globus -no-data-channel-authentication -no-third-party-transfers
