#!/usr/bin/env python3

"""
run several full space-time HQ evolution in heavy-ion collision:
    -- initial conditions (trento + HQ_sample) 
    -- hydro (VISHNew)
    -- HQ transport (Langevin)
    -- HQ hadronization 
    -- light hadron pricilization (osu-sampler)
    -- hadronic afterburner (UrQMD)
"""
from itertools import chain
import itertools
import sys, os
import subprocess

import numpy as np
import h5py
import shutil
from scipy.interpolate import interp1d


def run_cmd(*args, **kwargs):
    print(*args, flush=True)
    subprocess.check_call(
        list(chain.from_iterable(a.split() for a in args)),
        **kwargs
    )


def read_text_file(fileName):
    with open(fileName, 'rb') as f:
        return [l.split() for l in f if not l.startswith(b'#')]


def run_initial(nevents):
    run_cmd('./trento Pb Pb', str(nevents),
        '--cross-section 6.4',
        '--grid-max 13.05 --grid-step 0.1',
        '--normalization 132 --fluctuation 1.6 --nucleon-width 0.51',
        '--output initial', cwd='trento')


def run_hydro():
    run_cmd('./vishnew etas=0.08 etas_slope=0.75 vishbulknorm=1.1 edec=0.24', cwd='vishnew')

 

def run_HQsample():
    run_cmd('./HQ_sample HQ_sample.conf', cwd='HQ_sample')


def run_diffusion():
    os.environ['ftn10'] = 'dNg_over_dt_cD6.dat'
    os.environ['ftn20'] = 'HQ_AAcY.dat'
    os.environ['ftn30'] = 'initial_HQ.dat'
    run_cmd('./diffusion qhatMin=3.6 qhatSlope=14.11', cwd='diffusion')


def run_fragPLUSrecomb():
    os.environ['ftn20'] = 'Dmeson_AAcY.dat'
    child1 = 'cat HQ_AAcY.dat'
    p1 = subprocess.Popen(child1.split(), stdout = subprocess.PIPE)
    p2 = subprocess.Popen('./fragPLUSrecomb', stdin=p1.stdout)
    p1.stdout.close()
    output = p2.communicate()[0]


def participant_plane_angle():
    initialFile = 'initial.dat'
    pp_angleFile = 'pp_angle.dat'
    ed = np.loadtxt(initialFile)
    x_init = np.linspace(-13,13, 261)
    y_init = np.linspace(-13,13, 261)
    rx0, ry0 = np.meshgrid(x_init, y_init)
    x0 = np.sum(rx0 * ed) / np.sum(ed)
    y0 = np.sum(ry0 * ed) / np.sum(ed)
    rx = rx0 - x0
    ry = ry0 - y0

    r = np.sqrt(rx*rx + ry*ry)
    phi = np.arctan2(ry,rx)
    aver_cos = np.sum(r**2 * np.cos(2*phi) * ed) / np.sum(ed)
    aver_sin = np.sum(r**2 * np.sin(2*phi) * ed) / np.sum(ed)

    psi = 0.5*np.arctan2(aver_sin, aver_cos)
    pp_cos = np.cos(2*psi)
    pp_sin = np.sin(2*psi)
    astring = str(pp_cos) + '    ' + str(pp_sin)
    f = open(pp_angleFile, 'w')
    f.write(astring)
    f.close()


def bmsap_multi(collision_sys):
    sampleFile = 'sample_multi.in'
    if collision_sys == 'PbPb2760':
        spectraFile = 'spectra/updated/LHC2760-AA2ccbar.dat'
    elif collision_sys == 'PbPb5020':
        spectraFile = 'spectra/updated/LHC5020-AA2ccbar.dat'
    elif collision_sys == 'AuAu200':
        spectraFile = 'spectra/updated/RHIC200-AA2ccbar.dat'
    else:
        print('not a valid collision system!!')

    multiFile = 'multi_AAcY.dat' 
    DmesonFile = 'Dmeson_AAcY.dat'
    os.environ['ftn09'] = sampleFile
    os.environ['ftn10'] = spectraFile
    os.environ['ftn13'] = multiFile

    child2 = 'cat ' + DmesonFile
    p3 = subprocess.Popen(child2.split(), stdout = subprocess.PIPE)
    p4 = subprocess.Popen('./bmsap', stdin = p3.stdout)
    p3.stdout.close()
    output = p4.communicate()[0]

 
def bmsap_v2(collision_sys):
    sampleFile = 'sample.in'
    if collision_sys == 'PbPb2760':
        spectraFile = 'spectra/updated/LHC2760-AA2ccbar.dat'
    elif collision_sys == 'PbPb5020':
        spectraFile = 'spectra/updated/LHC5030-AA2ccbar.dat'
    elif colision_sys == 'AuAu200':
        spectraFile = 'spectra/updated/RHIC200-AA2ccbar.dat'
    else:
        print('not a valid collision system!!!')

    v2File = 'v2_AAcY.dat'
    DmesonFile = 'Dmeson_AAcY.dat'
    angleFile = 'pp_angle.dat'
    os.environ['ftn09'] = sampleFile
    os.environ['ftn10'] = spectraFile
    os.environ['ftn13'] = v2File
    os.environ['ftn24'] = angleFile
    child3 = 'cat ' + DmesonFile
    p5 = subprocess.Popen(child3.split(), stdout = subprocess.PIPE)
    p6 = subprocess.Popen('./bmsap', stdin=p5.stdout)
    p5.stdout.close()
    output = p6.communicate()[0]


def run_afterburner(ievent):
    surfaceFile = 'sampler/surface.dat'
    eventinfo_File = 'sampler/{0}.info.dat'.format(str(ievent))
    
    # now particalize the hypersurface
    if os.stat(surfaceFile).st_size == 0:
        print('empty hypersurface')
        return 0

    finfo = open(eventinfo_File, 'r')
    finfo.seek(0)
    for line in finfo:
        inputline = line.split()
        if len(inputline) > 1:
            if inputline[0] == 'mult':
                initial_mult = float(inputline[2])
            else:
                continue
        else:
            continue
    finfo.close()

    nsamples = min(max(int(2*1e5/initial_mult),2),100)

    run_cmd('./sampler oversamples={}'.format(nsamples), cwd='sampler')

    # a non-empty hypersurface can still emit zero particles. If no event produced by any particles, 
    # the output wil contain the three-line OSCAR header and nothing else. In this case, end the event here
    with open('sampler/oscar.dat', 'rb') as f:
        if next(itertools.islice(f,3,None), None) is None:
            print('no particles emitted')
            return 0
   
    run_cmd('./afterburner {} urqmd_final.dat'.format(nsamples), cwd='urqmd-afterburner')
    return nsamples


def Dmeson_Raa_v2(px, py, initial_pT, RaaFile, v2File):
    pT_AA, dsigmadpT2_AA = np.loadtxt('LHC2760-AA2ccbar.dat', unpack=True)
    dsigmadpT_AA = pT_AA * dsigmadpT2_AA
    sigma_AA = dsigmadpT_AA.sum() * (pT_AA[1] - pT_AA[0])
    dsigmadpT_AA = dsigmadpT_AA / sigma_AA
    dfdpT = interp1d(pT_AA, dsigmadpT_AA)
    pT_weight = dfdpT(initial_pT)

    final_pT = np.sqrt(px**2 + py**2)
    dNdpT, pT_bins = np.histogram(final_pT, bins=79, range=(0.5, 39.5), normed=True, weights=pT_weight)
    np.savetxt(RaaFile, (dNdpT, pT_bins[:-1]))


    pT_bins = np.linspace(0.5, 39.5, 79)
    if os.path.isfile('pp_angle.dat'):
        angle_ = np.loadtxt('pp_angle.dat')
        pp_cos = angle_[0]
        pp_sin = angle_[1]
    else:
        pp_cos = 1
        pp_sin = 0
    
    final_v2 = ((py**2 - px**2)*pp_cos + 2.*(px*py*pp_sin)) / (final_pT**2)
    final_v2_with_weight = final_v2 * pT_weight
    
    v2 = []
    for i in range(len(pT_bins)-1):
        cut = (final_pT > pT_bins[i]) & (final_pT < pT_bins[i+1])
        v2_sum = final_v2_with_weight[cut].sum() 
        weight_sum = pT_weight[cut].sum()
        v2.append(v2_sum/weight_sum)

    np.savetxt(v2File, (np.array(v2), pT_bins[:-1]))


def calculate_variable(urqmdFile, nsamples):
    species = [
        ('pion', 211),
        ('kaon', 321),
        ('proton', 2212)
    ]
    

    float_t = '<f8'
    int_t = '<i8'
    complex_t = '<c16'

    res = np.zeros(1, dtype=[
        ('nsamples', int_t),
        ('dNch_deta', float_t),
        ('dN_dy',[(s, float_t) for (s, _) in species]),
        ('mean_pT', [(s, float_t) for (s,_) in species]),
        ('M', int_t),
        ('Qn', complex_t, 6),
    ])

    res['nsamples'] = nsamples
    #----------------------------------------------------------------------
    ID, charge, mass, px, py, pz, y, eta, ipT, wt = (
        np.array(col, dtype=dtype) for (col, dtype) in 
        zip(
            zip(*read_text_file(urqmdFile)),
            (2*[int] + 8*[float])
        )
    )

    pT = np.sqrt(px**2 + py**2)
    phi = np.arctan2(py, px)
    abs_ID = np.abs(ID)
    abs_eta = np.fabs(eta)
    light_ID = ((abs_ID !=411) & (abs_ID !=412) & (abs_ID !=10411) & (abs_ID !=10412))
    charged = (charge != 0)
    Dmeson_ID = ((abs_ID == 411) | (abs_ID == 412) | (abs_ID == 10411) | (abs_ID == 10412))
    midrapidity = (np.fabs(y) < 0.5)

    res['dNch_deta'] = np.count_nonzero(charged & (abs_eta < 0.5) & light_ID) / nsamples
    phi_ALICE = phi[charged & (abs_eta < 0.8) & (pT > 0.2) & (pT < 5) & light_ID]
    res['M'] = phi_ALICE.size
    res['Qn'] = [np.exp(1j*n*phi_ALICE).sum() for n in range(1,7)]

    resultFile = 'result.dat'
    with open(resultFile, 'w') as fo:
        print('# nsamples ' + '%5d'%res['nsamples'], file=fo)
        print('# dNch_deta ' + '%10.3e'%res['dNch_deta'], file=fo)
        print('# M ' + '%10d'%res['M'], file=fo)
        print('# Q1 '+ str(res['Qn'][0][0]), file=fo)
        print('# Q2 '+ str(res['Qn'][0][1]), file=fo)
        print('# Q3 '+ str(res['Qn'][0][2]), file=fo)
        print('# Q4 '+ str(res['Qn'][0][3]), file=fo)
        print('# Q5 '+ str(res['Qn'][0][4]), file=fo)
        print('# Q6 '+ str(res['Qn'][0][5]), file=fo)

        outputline = '# {:8} {:8} {:8} {:16}'.format('ID', 'mean_pT', 'dN_dy', 'dN+dydpT/(2pi pT)')
        print(outputline, file=fo)
        for name, i in species:
            cut = (abs_ID == i) & midrapidity
            N = np.count_nonzero(cut)
            res['dN_dy'][name] = N/nsamples
            res['mean_pT'][name] = (0. if N==0 else pT[cut].mean())
            print(str(name) + '%10.5f' %res['mean_pT'][name] + '%10.3e'%res['dN_dy'][name], file=fo)

    #------------------------------------------------------------------------------------------------
    px_Dmeson = px[Dmeson_ID]
    py_Dmeson = py[Dmeson_ID]
    ipT_Dmeson = ipT[Dmeson_ID]
    RaaFile = 'multi_AAcY_urqmd.dat'
    v2File = 'v2_AAcY_urqmd.dat'
    Dmeson_Raa_v2(px_Dmeson, py_Dmeson, ipT_Dmeson, RaaFile, v2File)
    


def main():
    nevents = 10
    condor_ID = sys.argv[1]
    collision_sys = 'PbPb2760'

    run_initial(nevents)

    for ievent in range(nevents):
        postfix = '{0}-{1}.dat'.format(condor_ID, str(ievent))
        initialFile = 'trento/initial/{}.dat'.format(str(ievent))
        initial_info_File = 'trento/initial/{}.info.dat'.format(str(ievent))

        shutil.copyfile(initialFile, 'vishnew/initial.dat')
        shutil.copyfile(initialFile, 'bmsap/initial.dat')
        shutil.copyfile(initialFile, 'HQ_sample/initial.dat')
        shutil.move(initial_info_File, 'sampler/')

        run_hydro()
        shutil.move('vishnew/surface.dat', 'sampler/surface.dat')
        shutil.move('vishnew/JetCtl.dat', 'diffusion/JetCtl.dat')
        shutil.move('vishnew/JetData.dat', 'diffusion/JetData.dat')

        run_HQsample()
        shutil.move('HQ_sample/initial_HQ.dat', 'diffusion/initial_HQ.dat')

        run_diffusion()
        shutil.move('diffusion/HQ_AAcY.dat', 'fragPLUSrecomb/HQ_AAcY.dat')

        os.chdir('fragPLUSrecomb')
        run_fragPLUSrecomb()
        os.chdir('../')
        shutil.move('fragPLUSrecomb/Dmeson_AAcY.dat', 'bmsap/Dmeson_AAcY.dat')

        os.chdir('bmsap/')
        participant_plane_angle()
        bmsap_multi(collision_sys)
        bmsap_v2(collision_sys)
        os.chdir('../')
        shutil.move('bmsap/Dmeson_AAcY.dat', 'urqmd-afterburner/Dmeson_AAcY.dat')
        shutil.move('bmsap/pp_angle.dat', 'urqmd-afterburner/pp_angle.dat')

        nsamples = run_afterburner(ievent)

        if nsamples != 0:
            shutil.copyfile('bmsap/spectra/updated/LHC2760-AA2ccbar.dat', 'urqmd-afterburner/LHC2760-AA2ccbar.dat')
            os.chdir('urqmd-afterburner/')
            calculate_variable('urqmd_final.dat', nsamples)        
            os.chdir('../')
            shutil.move('urqmd-afterburner/urqmd_final.dat', 'results/urqmd_final'+postfix)
            shutil.move('urqmd-afterburner/result.dat', 'results/result'+postfix)
            shutil.move('sampler/{0}.info.dat'.format(str(ievent)), 'results/event_info'+postfix)
            #shutil.move('urqmd-afterburner/Dmeson_AAcY.dat', 'results/Dmeson_AAcY' + postfix)
            shutil.move('bmsap/multi_AAcY.dat', 'results/multi_AAcY'+postfix)
            shutil.move('bmsap/v2_AAcY.dat', 'results/v2_AAcY' + postfix)
            shutil.move('bmsap/initial.dat', 'results/initial' + postfix)
            shutil.move('urqmd-afterburner/pp_angle.dat', 'results/pp_angle'+postfix)
            shutil.move('urqmd-afterburner/multi_AAcY_urqmd.dat', 'results/multi_AAcY_urqmd'+postfix)
            shutil.move('urqmd-afterburner/v2_AAcY_urqmd.dat', 'results/v2_AAcY_urqmd'+postfix)

            continue
        else:
            print('No particle produced in this event')
            continue

if __name__ == "__main__":
    main()
            





